c:        program readray
        subroutine readray(gcarc,para,geom,time,tstar,ref_co)

c       subroutine for reading ray information from files
c
c       initial code read P, PP, PcP, S, SS, ScS wave ray information
c           from ray[1-6].info relatively. And 2-Dimension arrays
c           (gcarc(*,*) etc.) store those informations, ray type is
c           indicated by second index of array
c
c
c

        implicit none
        integer max_ray, raykind
        parameter (max_ray = 10000, raykind = 6)
        integer i,j
        integer raynum
        integer P,PP,PcP,S,SS,ScS
        character*20 inputfile
        character*1  rayindex
        real gcarc(max_ray,raykind), para(max_ray,raykind)
        real geom(max_ray,raykind), time(max_ray,raykind)
        real tstar(max_ray,raykind), ref_co(max_ray,raykind)
        
        real outpara,outgeom,outtime,outtstar,outref_co
        
        P   = 20    !handle of file generated by C program
        PP  = 21
        PcP = 22
        S   = 23
        SS  = 24
        ScS = 25
        
        do i = 1 , raykind
            write(rayindex, "(i1)") i
            inputfile = "ray"//rayindex//".info"
c            write(*,*) inputfile, rayindex
            open (i+20, file = inputfile(1:20), status = 'unknown')
            read (i+20, "(i6)") raynum
c            write (*,*) raynum
            do j = 1 , raynum-1
                read (i+20,*) gcarc(j,i),para(j,i),geom(j,i),
     &              time(j,i),tstar(j,i),ref_co(j,i)
            end do
            close (i+20)
        end do

c        call interpolation(60.,gcarc,para,geom,time,tstar,ref_co,
c     &  4,outpara,outgeom,outtime,outtstar,outref_co)

c        write(*,*) outpara,outgeom,outtime,outtstar,outref_co
        end subroutine
c        end program
